name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@v3
        with:
          github_user_name: ajeet-krish
          outputs: dist/github-snake.svg

      # Dark mode variant
      - uses: Platane/snk@v3
        with:
          github_user_name: ajeet-krish
          svg_out: dist/github-snake-dark.svg
          color_scheme: dark

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
